Use uuid5 associated with file SHA1 instead of randomly generated uuid4
hv0905/NekoImageGallery pull request #11
Opened 2023-12-30 13:52 UTC by pk5ls20

2023-12-30 15:04 UTC, hv0905 commented
Use the uuid5 directly will rewrite the old entry in database with the new entry directly, if two images have a same SHA1.

Maybe we should query the database to make sure the image doesn't exist in the db before copying and inserting?

2023-12-30 15:21 UTC, pk5ls20 commented
> If two images have the same SHA1, then using uuid5 directly will directly rewrite the old entry in the database with the new one.

Yes, but if the SHA1 of both images is the same, we can assume that both images are the same, **i.e. only necessary to index once**.

> Maybe we should query the database before copying and inserting to make sure the images don't exist in the database?

In a sense, doing this (i.e. querying the database to see if the same id entry already exists before inserting) won't affect the final contents of the database, but maybe it will **save indexing time**? 

I'll test the time difference between the two later

2023-12-30 21:43 UTC, pk5ls20 commented on scripts/local_indexing.py
> +                await copy_and_index_batch(filtered_list)
In the latest version of the implementation, when doing `local_indexing`, if the local and remote points have the same id value, this duplicate point will not be indexed

2023-12-30 21:47 UTC, pk5ls20 commented on app/Services/index_service.py
> +    async def index_image(self, image: Image.Image, image_data: ImageData, skip_ocr=False, allow_overwrite=False):
In index_image and index_image_batch, there is an `allow_overwrite=False` parameter to enable or disable duplicate checking, when duplicate checking is enabled and duplicates are detected, an exception will be thrown.

2023-12-31 04:44 UTC, hv0905 requested changes

2023-12-31 04:44 UTC, hv0905 commented on scripts/local_utility.py
> +def gather_valid_files(root: Path, pattern: str = '**/*.*', max_files=None):
Thumbnail generator is using this, we need to either make it return `Path` when `max_files=None` or refactor the thumbnail generator.

2023-12-31 06:59 UTC, hv0905 approved these changes

2023-12-31 15:15 UTC, pk5ls20 commented
@hv0905 I think this PR is now ready to be merged into master _(:з」∠)_

2023-12-31 17:57 UTC, hv0905 approved these changes

2023-12-31 17:57 UTC, merged